<a href="https://colab.research.google.com/github/chughtaianosh-boop/evolvix-aiml-internship-anoshchughtai/blob/main/Week_1/Week_1_Task_2_Anosh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine Learning Classification Task

This notebook performs a baseline machine learning classification task using `scikit-learn` to predict 'User Behavior Class' from the provided dataset.

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler # Import StandardScaler
import joblib

In [ ]:
# 1. Load the dataset named 'user_behavior_dataset.csv'
df = pd.read_csv('/content/user_behavior_dataset.csv')

# Display the first few rows to understand the data
print("Original DataFrame head:")
display(df.head())

Original DataFrame head:

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male,4
1,2,OnePlus 9,Android,268,4.7,1331,42,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male,2
3,4,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male,3
4,5,iPhone 12,iOS,187,4.3,1367,58,988,31,Female,3

In [ ]:
# 2. Define target variable and drop 'User ID'
X = df.drop(columns=['User ID', 'User Behavior Class']) # Features
y = df['User Behavior Class'] # Target variable

print("\nFeatures (X) head after dropping User ID and target:")
display(X.head())
print("\nTarget (y) head:")
display(y.head())

Features (X) head after dropping User ID and target:

,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender
0,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male
1,OnePlus 9,Android,268,4.7,1331,42,944,47,Female
2,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male
3,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male
4,iPhone 12,iOS,187,4.3,1367,58,988,31,Female

Target (y) head:

0    4
1    3
2    2
3    3
4    3
Name: User Behavior Class, dtype: int64

In [ ]:
# 3. Perform data preprocessing: Apply One-Hot Encoding to categorical features
# Identify categorical columns for one-hot encoding
categorical_cols = ['Operating System', 'Gender', 'Device Model']

# Apply one-hot encoding using pd.get_dummies
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True) # drop_first avoids multicollinearity

print("\nFeatures (X) head after One-Hot Encoding:")
display(X_encoded.head())

Features (X) head after One-Hot Encoding:

,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Operating System_iOS,Gender_Male,Device Model_OnePlus 9,Device Model_Samsung Galaxy S21,Device Model_Xiaomi Mi 11,Device Model_iPhone 12
0,393,6.4,1872,67,1122,40,False,True,False,False,False,False
1,268,4.7,1331,42,944,47,False,False,True,False,False,False
2,154,4.0,761,32,322,42,False,True,False,False,True,False
3,239,4.8,1676,56,871,20,False,True,False,False,False,False
4,187,4.3,1367,58,988,31,True,False,False,False,False,True

In [ ]:
# 4. Split the data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42, stratify=y
) # stratify=y ensures the same proportion of target class in train and test sets

# Scale numerical features after splitting to prevent data leakage
scaler = StandardScaler()
# Identify numerical columns in the encoded features (all non-boolean columns)
numerical_cols = X_train.select_dtypes(include=['number']).columns

X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

print(f"\nTraining features shape: {X_train.shape}")
print(f"Testing features shape: {X_test.shape}")
print(f"Training target shape: {y_train.shape}")
print(f"Testing target shape: {y_test.shape}")
print("Numerical features scaled successfully.")

Training features shape: (560, 12)
Testing features shape: (140, 12)
Training target shape: (560,)
Testing target shape: (140,)
Numerical features scaled successfully.

In [ ]:
# 5. Train a baseline Logistic Regression model
# Increase max_iter to ensure convergence, if a warning is thrown
model = LogisticRegression(max_iter=5000, random_state=42)
model.fit(X_train, y_train)

print("\nLogistic Regression model trained successfully.")

Logistic Regression model trained successfully.

In [ ]:
# 6. Evaluate the model on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted') # 'weighted' handles potential class imbalance
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"\nModel Evaluation on Test Set:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

Model Evaluation on Test Set:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000

In [ ]:
# 7. Save the trained model into a file named 'baseline_model.pkl'
joblib.dump(model, 'baseline_model.pkl')

print("\nModel successfully saved as 'baseline_model.pkl'")

Model successfully saved as 'baseline_model.pkl'